In [60]:
import pandas as pd

In [61]:
numbers=pd.Series([1,2,3,4,5])
numbers

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [62]:
data=[1,2,3,4,5]
for idx, val in enumerate(data):
    print(f"{idx}: {val}")
print(f"dtype: {type(val)}")

0: 1
1: 2
2: 3
3: 4
4: 5
dtype: <class 'int'>

In [63]:
products=pd.DataFrame([
 ['Mobile','Samsung','Rs.60000'],
 ['Laptop','Asus','Rs.150000'],
 ['TV', 'LG','Rs.50000'],
 ['Charger','MI','Rs.1000']
],
columns=['Product Name','Brand','Price'],
index=['A','B','C','D'])
products

  Product Name    Brand      Price
A       Mobile  Samsung   Rs.60000
B       Laptop     Asus  Rs.150000
C           TV       LG   Rs.50000
D      Charger       MI    Rs.1000

In [64]:
numbers.shape

(5,)

In [65]:
products.size

12

In [66]:
numbers[1:4:2] #start,stop,step

1    2
3    4
dtype: int64

In [67]:
products['B':'D'] #if we use row name instead of indexing then stop value is inclusive i.e. included

  Product Name Brand      Price
B       Laptop  Asus  Rs.150000
C           TV    LG   Rs.50000
D      Charger    MI    Rs.1000

# Loc and Iloc

In [68]:
'''
->used for slicing both row and col
LOC-> Location-> extract data using alphabetical index
ILOC-> Integer Location-> Extract data using numeric index
# No step in loc and iloc
'''

'\n->used for slicing both row and col\nLOC-> Location-> extract data using alphabetical index\nILOC-> Integer Location-> Extract data using numeric index\n# No step in loc and iloc\n'

In [69]:
products.iloc[1:3,1:]

  Brand      Price
B  Asus  Rs.150000
C    LG   Rs.50000

In [70]:
products.loc['B':'C','Brand':]

  Brand      Price
B  Asus  Rs.150000
C    LG   Rs.50000

In [71]:
products.iloc[
    [0,1,3],
    [0]
]

  Product Name
A       Mobile
B       Laptop
D      Charger

In [72]:
products.loc[
    ['A','B','D'],
    ['Product Name']
]

  Product Name
A       Mobile
B       Laptop
D      Charger

# Functions for file handling

## Read Files

In [ ]:
'''
CSV File-> read_csv(file_name.csv)
Excel File-> read_excel(file_name.csv)
JSON File-> read_json(file_name.csv)
SQL File-> read_sql(file_name.csv)

'''

## Create Files

In [ ]:
'''
CSV File-> to_csv(file_name.csv, index=False)
Excel File-> to_excel(file_name.csv, index=False)
JSON File-> to_json(file_name.csv, index=4)

'''

## Read File

In [73]:
df = pd.read_csv('D:\Data Science\Dataset\Cardiovascular_Disease.csv')
df

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\Acer\AppData\Local\Temp\ipykernel_1724\52638603.py:1: SyntaxWarning: invalid escape sequence '\D'
  df = pd.read_csv('D:\Data Science\Dataset\Cardiovascular_Disease.csv')

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,99993,19240,2,168,76.0,120,80,1,1,1,0,1,0
69996,99995,22601,1,158,126.0,140,90,2,2,0,0,1,1
69997,99996,19066,2,183,105.0,180,90,3,1,0,1,0,1
69998,99998,22431,1,163,72.0,135,80,1,2,0,0,0,1
69999,99999,20540,1,170,72.0,120,80,2,1,0,0,1,0

In [ ]:
df.head() #top 5 by default

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0

In [75]:
df.tail() # bottom 5 by default

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
69995,99993,19240,2,168,76.0,120,80,1,1,1,0,1,0
69996,99995,22601,1,158,126.0,140,90,2,2,0,0,1,1
69997,99996,19066,2,183,105.0,180,90,3,1,0,1,0,1
69998,99998,22431,1,163,72.0,135,80,1,2,0,0,0,1
69999,99999,20540,1,170,72.0,120,80,2,1,0,0,1,0

In [ ]:
df.head(10) #shows top 10 data
# if more than 60 then it doesnt show full shows ...

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0
5,8,21914,1,151,67.0,120,80,2,2,0,0,0,0
6,9,22113,1,157,93.0,130,80,3,1,0,0,1,0
7,12,22584,2,178,95.0,130,90,3,3,0,0,1,1
8,13,17668,1,158,71.0,110,70,1,1,0,0,1,0
9,14,19834,1,164,68.0,110,60,1,1,0,0,0,0

In [79]:
df.tail(60)

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
69940,99911,21307,1,168,78.0,140,80,3,1,0,0,1,1
69941,99915,16854,1,166,83.0,120,80,1,1,0,0,1,0
69942,99916,19614,1,162,74.0,120,80,1,1,0,0,1,1
69943,99919,22570,2,160,55.0,140,90,2,1,0,0,1,1
69944,99922,23464,2,170,97.0,130,90,2,1,0,0,1,1
69945,99923,21397,1,150,71.0,110,80,1,1,0,0,1,0
69946,99925,21333,1,164,115.0,130,80,1,1,0,0,1,1
69947,99930,23305,2,172,113.0,110,80,1,1,0,0,0,1
69948,99931,20388,1,164,90.0,130,80,1,1,0,0,1,1
69949,99932,22119,1,167,68.0,167,85,3,1,0,0,1,1
69950,99933,19137,2,167,74.0,130,80,1,1,1,1,1,0
69951,99934,15254,1,158,55.0,110,70,1,1,0,0,1,0
69952,99935,19727,1,172,75.0,120,80,1,1,0,0,1,1
69953,99936,17373,2,173,69.0,110,70,1,1,1,1,1,1
69954,99938,15151,1,170,60.0,120,80,2,1,0,0,1,0
69955,99939,21726,1,164,88.0,140,90,1,1,0,0,1,0
69956,99940,21453,1,158,75.0,120,80,3,3,0,0,1,0
69957,99941,15536,2,166,90.0,120,80,1,1,1,0,1,0
69958,99943,15239,2,169,67.0,160,90,1,1,0,0,1,1
69959,99945,19069,1,163,64.0,130,70,1,1,0,0,1,1
69960,99947,20587,2,169,79.0,140,90,1,1,0,0,0,1
69961,99948,16598,1,161,50.0,110,75,1,1,0,0,1,0
69962,99949,21151,1,178,69.0,130,90,1,1,0,0,1,1
69963,99950,19538,2,155,76.0,130,90,1,1,0,0,1,0
69964,99951,22491,2,170,72.0,120,80,1,1,0,0,0,1
69965,99952,15450,2,165,66.0,120,80,1,1,0,0,0,0
69966,99954,20327,1,156,67.0,140,80,2,1,0,0,0,0
69967,99955,21416,2,168,63.0,140,1000,1,1,0,0,1,1
69968,99956,16093,2,157,61.0,110,90,1,1,0,0,1,0
69969,99957,20529,2,175,78.0,120,80,1,1,0,0,0,0
69970,99958,22572,2,173,103.0,140,80,3,1,1,1,0,1
69971,99959,20136,2,177,80.0,130,80,1,1,0,0,1,0
69972,99960,17065,1,165,76.0,140,90,1,1,0,0,1,1
69973,99961,22142,2,175,72.0,130,80,1,1,0,0,1,0
69974,99962,18226,1,168,75.0,120,80,1,1,0,0,1,0
69975,99963,21264,2,182,100.0,120,80,1,1,0,0,1,1
69976,99964,21699,1,163,65.0,120,80,2,2,0,0,1,0
69977,99965,16843,1,168,75.0,120,79,1,1,0,0,1,0
69978,99967,18800,1,163,78.0,90,60,1,1,0,0,1,1
69979,99969,22423,1,163,74.0,160,100,2,2,0,0,1,1
69980,99971,17727,2,167,69.0,110,80,1,1,0,1,0,0
69981,99972,17500,2,182,110.0,130,90,2,2,0,0,1,1
69982,99973,18941,1,153,86.0,130,90,1,2,0,0,1,1
69983,99974,19652,1,165,72.0,120,80,1,1,0,0,1,0
69984,99975,17926,2,168,80.0,120,80,1,1,0,0,1,1
69985,99977,18194,1,156,102.0,130,80,1,1,0,1,0,1
69986,99978,18198,2,180,78.0,120,80,1,1,0,0,1,0
69987,99979,18852,1,151,49.0,120,80,1,1,0,0,1,0
69988,99981,21978,1,160,59.0,110,70,1,1,0,0,1,0
69989,99985,21013,1,157,83.0,120,70,1,1,0,0,1,1
69990,99986,15094,1,168,72.0,110,70,1,1,0,0,1,1
69991,99988,20609,1,159,72.0,130,90,2,2,0,0,1,0
69992,99990,18792,1,161,56.0,170,90,1,1,0,0,1,1
69993,99991,19699,1,172,70.0,130,90,1,1,0,0,1,1
69994,99992,21074,1,165,80.0,150,80,1,1,0,0,1,1
69995,99993,19240,2,168,76.0,120,80,1,1,1,0,1,0
69996,99995,22601,1,158,126.0,140,90,2,2,0,0,1,1
69997,99996,19066,2,183,105.0,180,90,3,1,0,1,0,1
69998,99998,22431,1,163,72.0,135,80,1,2,0,0,0,1
69999,99999,20540,1,170,72.0,120,80,2,1,0,0,1,0

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           70000 non-null  int64
 1   age          70000 non-null  int64
 2   gender       70000 non-null  int64
 3   height       70000 non-null  int64
 4   weight       70000 non-null  float64
 5   ap_hi        70000 non-null  int64
 6   ap_lo        70000 non-null  int64
 7   cholesterol  70000 non-null  int64
 8   gluc         70000 non-null  int64
 9   smoke        70000 non-null  int64
 10  alco         70000 non-null  int64
 11  active       70000 non-null  int64
 12  cardio       70000 non-null  int64
dtypes: float64(1), int64(12)
memory usage: 6.9 MB

In [81]:
emp = pd.read_csv('Dataset/Employees.csv')
emp.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0

In [82]:
emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EMPLOYEE_ID     111 non-null    int64
 1   FIRST_NAME      111 non-null    object
 2   LAST_NAME       111 non-null    object
 3   EMAIL           111 non-null    object
 4   PHONE_NUMBER    111 non-null    object
 5   HIRE_DATE       111 non-null    object
 6   JOB_ID          111 non-null    object
 7   SALARY          111 non-null    int64
 8   COMMISSION_PCT  35 non-null     float64
 9   MANAGER_ID      110 non-null    float64
 10  DEPARTMENT_ID   110 non-null    float64
dtypes: float64(3), int64(2), object(6)
memory usage: 9.7+ KB

## Null values

In [ ]:
'''
NaN-> Not a number-> Numeric/Alphabetical
NaT-> Not a time-> Date/Time
'''