# Support Vector Mavhine (SVM)

In [ ]:
'''
-> both regression and classification tasks.
-> only for very small data (even 20k data is more for this.)
-> SVR and SVC
-> while using SVM for large data let 70k data then we take a small sample (like 5k , 10k data) from the data.
-> SVM not preferred for very large data sets.

-> Model Parameters
    -> Kernel = (linear, rbf, poly)
    -> C = (0.01, 0.1, 1.0, 10, 100)
    -> Gamma = (0.01, 0.1, 1.0, scale, 10)

    linear->linearly separable data
    rbf-> make curve line instead of straight line when line linearly not separable
        -> Radial Basis Function
    C-> line thickness (used for all liblinear, rbf, poly)
    Gamma-> used for rbf (to define line smoothness)
    
-> for SVM classification (ie., SVC )-> use stratify
'''

'\n-> both regression and classification tasks.\n-> only for very small data (even 20k data is more for this.)\n-> SVR and SVC\n-> while using SVM for large data let 70k data then we take a small sample (like 5k , 10k data) from the data.\n-> SVM not preferred for very large data sets.\n\n-> Model Parameters\n    -> Kernel = (linear, rbf, poly)\n    -> C = (0.01, 0.1, 1.0, 10, 100)\n    -> Gamma = (0.01, 0.1, 1.0, scale, 10)\n\n    linear->linearly separable data\n    rbf-> make curve line instead of straight line when line linearly not separable\n    C-> line thickness (used for all liblinear, rbf, poly)\n    Gamma-> used for rbf (to define line smoothness)\n    \n-> for SVM classification (ie., SVC )-> use stratify\n'

In [130]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Import SVM Model
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix

In [131]:
df = pd.read_csv('D:\Data Science\Dataset\Cardiovascular_Disease.csv')

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\Acer\AppData\Local\Temp\ipykernel_19116\1963838193.py:1: SyntaxWarning: invalid escape sequence '\D'
  df = pd.read_csv('D:\Data Science\Dataset\Cardiovascular_Disease.csv')

In [132]:
df.head()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0

In [133]:
df['age'] = df['age']//365

In [134]:
filtered_df = df[
    (df['height'].between(150,190))&
    (df['weight'].between(45,110))&
    (df['ap_hi'].between(90,180))&
    (df['ap_lo'].between(50,90))
]

In [135]:
df_sample = filtered_df.sample(n=6000, random_state=42)
df_sample

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
45845,65482,58,1,168,68.0,120,80,3,3,0,0,0,0
60877,86894,57,2,185,102.0,130,85,1,1,0,0,1,0
69901,99845,53,1,165,71.0,120,70,1,1,0,0,1,1
41468,59252,64,2,165,69.0,130,80,1,1,0,0,0,0
68951,98507,47,2,168,64.0,120,80,1,1,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
42364,60521,60,2,174,77.0,160,60,1,1,0,0,1,1
56506,80653,61,1,164,59.0,140,80,2,1,0,0,1,1
15438,22066,58,1,170,70.0,120,80,1,1,0,0,1,1
23485,33557,52,2,168,71.0,160,80,1,1,1,0,1,1
33466,47810,51,2,174,84.0,125,80,1,1,1,0,1,0

In [136]:
df_sample.columns

Index(['id', 'age', 'gender', 'height', 'weight', 'ap_hi', 'ap_lo',
       'cholesterol', 'gluc', 'smoke', 'alco', 'active', 'cardio'],
      dtype='object')

## Feature and Target

In [137]:
features = [ 'age', 'gender', 'height', 'weight', 'ap_hi', 'ap_lo',
       'cholesterol', 'gluc', 'smoke', 'alco', 'active']
target = 'cardio'

In [138]:
X = df_sample[features]
Y = df_sample[target]

## Train Test Split

In [139]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X,Y, test_size=0.2, random_state=42, stratify=Y
)

## Feature Scaling

In [140]:
scaler = StandardScaler()
X_train_scale = scaler.fit_transform(X_train)
X_test_scale = scaler.transform(X_test)

## Model Implementation

In [141]:
model = SVC(
    kernel= 'linear', 
    C=1.0,
    gamma='scale'
)
model.fit(X_train_scale, Y_train)

SVC(kernel='linear')

In [142]:
Y_pred = model.predict(X_test_scale)
Y_pred

array([1, 0, 0, ..., 0, 1, 0], dtype=int64)

In [143]:
cm = confusion_matrix(Y_test, Y_pred)
cr = classification_report(Y_test, Y_pred)

In [144]:
print(cm)

[[541 106]
 [223 330]]

In [145]:
print(cr)

              precision    recall  f1-score   support

           0       0.71      0.84      0.77       647
           1       0.76      0.60      0.67       553

    accuracy                           0.73      1200
   macro avg       0.73      0.72      0.72      1200
weighted avg       0.73      0.73      0.72      1200

## New Data Prediction

In [146]:
data ={
    'age':[30,45,39],
    'gender':[1,2,1],
    'height':[151, 160, 157], 
    'weight':[60, 70, 50],
    'ap_hi':[120, 140, 160],
    'ap_lo':[90, 80, 60],
    'cholesterol':[1,3,2],
    'gluc':[1,1,2],
    'smoke':[0, 1,1],
    'alco':[1,1,1],
    'active':[0,1,0]
}

In [147]:
input_data = pd.DataFrame(data)
input_data

,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active
0,30,1,151,60,120,90,1,1,0,1,0
1,45,2,160,70,140,80,3,1,1,1,1
2,39,1,157,50,160,60,2,2,1,1,0

In [148]:
input_scale = scaler.transform(input_data)
pred = model.predict(input_scale)
input_data['cardio_pred'] = pred

In [149]:
input_data

,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio_pred
0,30,1,151,60,120,90,1,1,0,1,0,0
1,45,2,160,70,140,80,3,1,1,1,1,1
2,39,1,157,50,160,60,2,2,1,1,0,1